# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ensure admissibility of the GPD scale parameter
#' up to now only for positive shape parameters
#'
#' @inheritParams compute_nll_gpd
#' @return isotonic scale parameter that does not violate the GPD constraint
MakeScaleAdmissible <- function(scale, y, shape) {
    .Call('gpdIcm_MakeScaleAdmissible', PACKAGE = 'gpdIcm', scale, y, shape)
}

#' Isotonic estimation (using an adapted version of the ICM algorithm)
#'
#' @return isotonic scale parameter estimate and deviance
#' @inheritParams compute_nll_gpd
#' @param start Numeric vector of the initial scale parameters (will be forced to be admissible)
#' @param max_repetitions Maximal number of repetitions
#' @useDynLib gpdIcm
#' @importFrom Rcpp evalCpp
#' @export
FitIsoScaleFixedICM <- function(y, start, shape, max_repetitions = 1e+5L) {
    .Call('gpdIcm_FitIsoScaleFixedICM', PACKAGE = 'gpdIcm', y, start, shape, max_repetitions)
}

#' Isotonic estimation (using a projected gradient method)
#'
#' @note up to now only for positive shape parameters
#'
#' @inheritParams compute_nll_gpd
#' @inheritParams FitIsoScaleFixedICM
#' @return isotonic scale parameter estimate and deviance
#' @export
gpd_isotonic_scale_projected_gradient <- function(y, scale, shape, max_repetitions = 1e+5L) {
    .Call('gpdIcm_gpd_isotonic_scale_projected_gradient', PACKAGE = 'gpdIcm', y, scale, shape, max_repetitions)
}

#' Estimation of GPD parameters with constant shape parameter and non-decreasing
#' scale parameter 
#'
#' @inheritParams compute_nll_gpd
#' @inheritParams FitIsoScaleFixedICM
#' @param min_shape double minimum shape value
#' @param max_shape double maximum shape value
#' @param by double step size for the profile likelihood 
#' @return isotonic scale parameter estimate and deviance
#' @export
FitIsoScaleGPD <- function(y, min_shape, max_shape, by = 0.01, max_repetitions = 1e+5L) {
    .Call('gpdIcm_FitIsoScaleGPD', PACKAGE = 'gpdIcm', y, min_shape, max_shape, by, max_repetitions)
}

#' Computes the negative log likelihood for the GPD
#' 
#' No threshold parameter
#' 
#' scale has same length as y and shape has length 1
#' @param y numeric vector of the data
#' @param scale numeric vector of the scape parameters
#' @param shape double 
compute_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Computes the first partial derivative (scale) of the negative log likelihood for the GPD 
#' 
#' No threshold parameter
#' 
#' scale has same length as y and shape has length 1
#' @inheritParams compute_nll_gpd
compute_pd1_scale_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_pd1_scale_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

