# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ensure admissibility of the GPD scale parameter
#' up to now only for positive shape parameters
#'
#' @inheritParams compute_nll_gpd
#' @return isotonic scale parameter that does not violate the GPD constraint
make_gpd_admissible <- function(scale, y, shape) {
    .Call('gpdIcm_make_gpd_admissible', PACKAGE = 'gpdIcm', scale, y, shape)
}

#' Isotonic estimation (using an adapted version of the ICM algorithm)
#'
#' @return isotonic scale parameter estimate and deviance
#' @inheritParams compute_nll_gpd
#' @param start Numeric vector of the initial scale parameters (will be forced to be admissible)
#' @useDynLib gpdIcm
#' @importFrom Rcpp evalCpp
#' @export
gpd_scale_isotonic_fit <- function(y, start, shape) {
    .Call('gpdIcm_gpd_scale_isotonic_fit', PACKAGE = 'gpdIcm', y, start, shape)
}

#' Isotonic estimation (using a projected grdient method)
#'
#' @note up to now only for positive shape parameters
#'
#' @inheritParams compute_nll_gpd
#' @return isotonic scale parameter estimate and deviance
gpd_isotonic_scale_projected_gradient <- function(y, scale, shape) {
    .Call('gpdIcm_gpd_isotonic_scale_projected_gradient', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Estimation of GPD parameters with fixed shape parameter and non-decreasing scale parameter 
#'
#'
#' @inheritParams compute_nll_gpd
#' @return isotonic scale parameter estimate and deviance
#' @export
isotonic_scale_gpd_estimator <- function(y, shape) {
    .Call('gpdIcm_isotonic_scale_gpd_estimator', PACKAGE = 'gpdIcm', y, shape)
}

#' Computes the negative log likelihood for the GPD
#' 
#' No threshold parameter
#' 
#' scale has same length as y and shape has length 1
#' @param y numeric vector of the data
#' @param scale numeric vector of the scape parameters
#' @param shape double 
compute_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Computes the first partial derivative (scale) of the negative log likelihood for the GPD 
#' 
#' No threshold parameter
#' 
#' scale has same length as y and shape has length 1
#' @inheritParams compute_nll_gpd
compute_pd1_scale_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_pd1_scale_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

