# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ensure admissibility of the GPD scale parameter
#' up to now only for positive shape parameters
#'
#' @inheritParams compute_nll_gpd
#' @return isotonic scale parameter that does not violate the GPD constraint
#' @useDynLib gpdIcm
#' @importFrom Rcpp evalCpp
MakeScaleAdmissible <- function(scale, y, shape) {
    .Call('gpdIcm_MakeScaleAdmissible', PACKAGE = 'gpdIcm', scale, y, shape)
}

compute_scalar_product <- function(a, b) {
    .Call('gpdIcm_compute_scalar_product', PACKAGE = 'gpdIcm', a, b)
}

ComputeGradient <- function(y, scale, shape) {
    .Call('gpdIcm_ComputeGradient', PACKAGE = 'gpdIcm', y, scale, shape)
}

ComputeHessianDiagonal <- function(y, scale, shape) {
    .Call('gpdIcm_ComputeHessianDiagonal', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Isotonic estimation (using a projected gradient method)
#'
#' @note up to now only for positive shape parameters
#'
#' @inheritParams compute_nll_gpd
#' @inheritParams FitIsoScaleFixedICM
#' @return isotonic scale parameter estimate, deviance, convergence, iterations
#' and deviance trace
#' @export
FitIsoScaleFixedPG <- function(y, scale, shape, max_repetitions = 1e+5L) {
    .Call('gpdIcm_FitIsoScaleFixedPG', PACKAGE = 'gpdIcm', y, scale, shape, max_repetitions)
}

generate_shape_grid <- function(from_, to_, by_ = 0.01) {
    .Call('gpdIcm_generate_shape_grid', PACKAGE = 'gpdIcm', from_, to_, by_)
}

#' Computes the negative log likelihood for the GPD
#' 
#' No threshold parameter
#' 
#' scale has same length as y and shape has length 1
#' @param y numeric vector of the data
#' @param scale numeric vector of the scape parameters
#' @param shape double 
#' @export
compute_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Computes the first partial derivative (scale) of the negative log likelihood for the GPD 
#' 
#' No threshold parameter
#' 
#' scale has same length as y and shape has length 1
#' @inheritParams compute_nll_gpd
compute_pd1_scale_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_pd1_scale_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Computes the second partial derivative (scale) of the negative
#' log likelihood for the GPD
#' @inheritParams compute_nll_gpd
compute_pd2_scale_nll_gpd <- function(y, scale, shape) {
    .Call('gpdIcm_compute_pd2_scale_nll_gpd', PACKAGE = 'gpdIcm', y, scale, shape)
}

#' Computes the convex minorant of a polygon.
#' @param x,y the coordinates of the polygon
#' @return vector of the y-coordinates of the convex minorant
convexMinorant <- function(x, y) {
    .Call('gpdIcm_convexMinorant', PACKAGE = 'gpdIcm', x, y)
}

#' Computes the convex minorant of a vector.
#' @param x,y Vector of x and y values
#' @return x.knots, y.knots, y.slopes and the left derivative at all x values
#' @export
GreatestConvexMinorant <- function(x, y) {
    .Call('gpdIcm_GreatestConvexMinorant', PACKAGE = 'gpdIcm', x, y)
}

